GitStreamSecrets: ${ssm:/aws/reference/secretsmanager/default/GitStreamSecrets}
GS_GH_APP_PRIVATE_KEY: ${ssm:/aws/reference/secretsmanager/default/GS_GH_APP_PRIVATE_KEY}
BACKFILL_TOKEN: ${ssm:/aws/reference/secretsmanager/BACKFILL_TOKEN}
