ENV: ${opt:stage}
NODE_ENV: production
GS_WEBHOOKS_Q_URL: ${ssm:/GS_WEBHOOKS_Q_URL}
GS_ACTIONS_GITHUB_Q_URL: ${ssm:/GS_ACTIONS_GITHUB_Q_URL}
GH_APP_ID: ${ssm:/GH_APP_ID}
GH_APP_USER_ID: ${ssm:/GH_APP_USER_ID}
GITSTREAM_RULES_RESOLVER_URL: ${ssm:/GITSTREAM_RULES_RESOLVER_URL}
GITSTREAM_ANALYTICS_URL: ${ssm:/GITSTREAM_ANALYTICS_URL}
