name: PUSH Workflow

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
jobs:
  main-job:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [16.13.2]

    steps:
      - name: Sleep 10
        run: sleep 10s
      - name: Sleep 30
        run: sleep 30s
